ServiceNotFound=                     "Service {{service}} is not found"
OperationNotFound=                   "Operation {{operation}} in service {{service}} not found"
DecodingError=                       "Error in decoding the request. error = {{error}}"
CannotGenerateHTTPRequest=           "unable to generate HTTP request for param {{param}}. error is {{error}}"
CannotGenerateHTTPRequest1=          "unable to generate HTTP request. error is {{error}}"
CannotGenerateHTTPRequestForPayload= "Cannot construct the message from payload {{error}}"
ResponseUnmarshalException=          "Unable to unmarshal response payload.Error = {{error}}"
ParamsNotExpected=                   "#params passed does not match expected. Actual = {{actual}}. Expected = {{expected}}"
HTTPCallFailed=                      "http call failed. err = {{error}}"
CannotReadResponseBody=              "cannot read response body err = {{error}}"
CannotMakeStateEntity=              "cannot make the state entity. error = {{error}}"
ErrorInDecoding=                     "Error in decoding request"
ErrorInAutoState=                    "automatic state for {{state}} threw error {{error}}"
AutoStateNotConfigured=              "autostate {{state}} is not configured in the action catalog"
InvalidState=                        "invalid state {{state}} returned by the entity"
InvalidEvent=                        "invalid event {{event}} for the current state {{state}}"
CannotReadFile=                      "Cannot read file {{file}}. Erorr = {{error}}"
EventNotFoundInRequest =             "Cannot find event in the request."
ParameterMissingInRequest=           "Parameter {{param}} is missing in request"
ErrorInObtainingSTM=                "Error in Obtaining STM"