// Code generated by "stringer -linecomment -type=WegoErrorCode"; DO NOT EDIT.

package err

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ServiceNotFound-1000]
	_ = x[OperationNotFound-1001]
	_ = x[DecodingError-1002]
	_ = x[CannotGenerateHTTPRequest-1003]
	_ = x[CannotGenerateHTTPRequest1-1004]
	_ = x[CannotGenerateHTTPRequestForPayload-1005]
	_ = x[ResponseUnmarshalException-1006]
	_ = x[ParamsNotExpected-1007]
	_ = x[HTTPCallFailed-1008]
	_ = x[CannotReadResponseBody-1009]
	_ = x[CannotMakeStateEntity-1010]
	_ = x[ErrorInDecoding-1011]
	_ = x[ErrorInAutoState-1012]
	_ = x[AutoStateNotConfigured-1013]
	_ = x[InvalidState-1014]
	_ = x[InvalidEvent-1015]
	_ = x[CannotReadFile-1016]
	_ = x[EventNotFoundInRequest-1017]
	_ = x[ParameterMissingInRequest-1018]
	_ = x[ErrorInObtainingSTM-1019]
	_ = x[Non200StatusCodeReturned-1020]
	_ = x[ValidationError-1021]
	_ = x[UnparseableFile-1022]
	_ = x[ErrorInInvokingService-1023]
}

const _BPlusErrorCode_name = "bplus.errors.ServiceNotFoundbplus.errors.OperationNotFoundbplus.errors.DecodingErrorbplus.errors.CannotGenerateHTTPRequestbplus.errors.CannotGenerateHTTPRequest1bplus.errorsbplus.errors.CannotGenerateHTTPRequestForPayloadbplus.errors.ParamsNotExpectedbplus.errors.HTTPCallFailedbplus.errors.CannotReadResponseBodybplus.errors.CannotMakeStateEntitybplus.errors.ErrorInDecodingbplus.errors.ErrorInAutoStatebplus.errors.AutoStateNotConfiguredbplus.errors.InvalidStatebplus.errors.InvalidEventbplus.errors.CannotReadFilebplus.errors.EventNotFoundInRequestbplus.errors.ParameterMissingInRequestbplus.errors.ErrorInObtainingSTMbplus.errors.Non200StatusCodeReturnedbplus.errors.ValidationErrorbplus.error.UnparseableFilebplus.error.ErrorInInvokingService"

var _BPlusErrorCode_index = [...]uint16{0, 28, 58, 84, 122, 161, 173, 221, 251, 278, 313, 347, 375, 404, 439, 464, 489, 516, 551, 589, 621, 658, 686, 713, 747}

func (i WegoErrorCode) String() string {
	i -= 1000
	if i < 0 || i >= WegoErrorCode(len(_BPlusErrorCode_index)-1) {
		return "WegoErrorCode(" + strconv.FormatInt(int64(i+1000), 10) + ")"
	}
	return _BPlusErrorCode_name[_BPlusErrorCode_index[i]:_BPlusErrorCode_index[i+1]]
}
