// Code generated by "stringer -linecomment -type=WegoErrorCode"; DO NOT EDIT.

package err

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ServiceNotFound-1000]
	_ = x[OperationNotFound-1001]
	_ = x[DecodingError-1002]
	_ = x[CannotGenerateHTTPRequest-1003]
	_ = x[CannotGenerateHTTPRequest1-1004]
	_ = x[CannotGenerateHTTPRequestForPayload-1005]
	_ = x[ResponseUnmarshalException-1006]
	_ = x[ParamsNotExpected-1007]
	_ = x[HTTPCallFailed-1008]
	_ = x[CannotReadResponseBody-1009]
	_ = x[CannotMakeStateEntity-1010]
	_ = x[ErrorInDecoding-1011]
	_ = x[ErrorInAutoState-1012]
	_ = x[AutoStateNotConfigured-1013]
	_ = x[InvalidState-1014]
	_ = x[InvalidEvent-1015]
	_ = x[CannotReadFile-1016]
	_ = x[EventNotFoundInRequest-1017]
	_ = x[ParameterMissingInRequest-1018]
	_ = x[ErrorInObtainingSTM-1019]
	_ = x[Non200StatusCodeReturned-1020]
	_ = x[ValidationError-1021]
	_ = x[UnparseableFile-1022]
	_ = x[ErrorInInvokingService-1023]
}

const _WegoErrorCode_name = "wego.errors.ServiceNotFoundwego.errors.OperationNotFoundwego.errors.DecodingErrorwego.errors.CannotGenerateHTTPRequestwego.errors.CannotGenerateHTTPRequest1wego.errorswego.errors.CannotGenerateHTTPRequestForPayloadwego.errors.ParamsNotExpectedwego.errors.HTTPCallFailedwego.errors.CannotReadResponseBodywego.errors.CannotMakeStateEntitywego.errors.ErrorInDecodingwego.errors.ErrorInAutoStatewego.errors.AutoStateNotConfiguredwego.errors.InvalidStatewego.errors.InvalidEventwego.errors.CannotReadFilewego.errors.EventNotFoundInRequestwego.errors.ParameterMissingInRequestwego.errors.ErrorInObtainingSTMwego.errors.Non200StatusCodeReturnedwego.errors.ValidationErrorwego.error.UnparseableFilewego.error.ErrorInInvokingService"

var _WegoErrorCode_index = [...]uint16{0, 27, 56, 81, 118, 156, 167, 214, 243, 269, 303, 336, 363, 391, 425, 449, 473, 499, 533, 570, 601, 637, 664, 690, 723}

func (i WegoErrorCode) String() string {
	i -= 1000
	if i < 0 || i >= WegoErrorCode(len(_WegoErrorCode_index)-1) {
		return "WegoErrorCode(" + strconv.FormatInt(int64(i+1000), 10) + ")"
	}
	return _WegoErrorCode_name[_WegoErrorCode_index[i]:_WegoErrorCode_index[i+1]]
}
