[wego]

DEFAULTLANGUAGE="en-US"
etcd_endpoint="localhost:2379"
etcd_polling_delay=30

# These must be pushed to etcd or similar with crypt enabled
application_name= "WeGO"
new_relic_license_key = ""
new_relic_enabled = true

# Logger settings
log_level="debug"
development_mode=true
disable_caller=false
disable_stacktrace=false

# Port etc.
port="5000"