[bplus]

DEFAULTLANGUAGE="en-US"
etcd_endpoint="localhost:2379"
etcd_polling_delay=30

# These must be pushed to etcd or similar with crypt enabled
application_name= "BPLUS"
new_relic_license_key = "7aa28548d17b112983b08e9fb1a441bfd96fNRAL"
new_relic_enabled = true

# Logger settings
log_level="debug"
development_mode=true
disable_caller=false
disable_stacktrace=false